# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '音视频项目' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 音视频项目

  #pod 'Masonry'

end
